### ISSUE TITLE
执行命令```npm run electron:build```报错

### ISSUE THREAD

**Issue by fatinghenji** [TachibanaKimika/umamusume-calc#2]
报错如下：
```
 ERROR  Error: Cannot find module 'fs/promises'
Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/umamusume-calc/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/umamusume-calc/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umamusume-calc@0.1.0 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the umamusume-calc@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-06T18_23_47_737Z-debug.log
```
log文件如下：
[2021-08-06T18_23_47_737Z-debug.log](https://github.com/TachibanaKimika/umamusume-calc/files/6947573/2021-08-06T18_23_47_737Z-debug.log)

**Comment by TachibanaKimika** [comment]
试试升级一下你node的版本, 我的是v14.17.0 [stackoverflow](https://stackoverflow.com/questions/68085375/cannot-find-module-fs-promises-electron-js)
